import React from 'react';
import {
  Calendar,
  Users,
  FileText,
  MapPin,
  Plus,
  Wrench,
  Settings,
  TrendingUp,
  MessageSquare,
  Clock,
  Building,
  Grid,
  Target,
  CheckCircle2,
  Star,
  Zap,
  BookOpen,
  Bell,
  Shield,
} from 'lucide-react-native';
import { Colors } from '@/constants/colors';
import { ProgressiveTourStep } from '@/components/ProgressiveTour';

export const ownerProgressiveTour: ProgressiveTourStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to Your Business Hub',
    description: 'Let\'s take a quick tour to help you get started managing your HVAC/refrigeration business efficiently.',
    icon: <Wrench size={32} color={Colors.primary} />,
    targetRoute: '/',
    position: 'center',
  },
  {
    id: 'dashboard-intro',
    title: 'Your Command Center',
    description: 'This is your dashboard. Here you\'ll see today\'s schedule, upcoming jobs, and real-time business stats at a glance.',
    icon: <Grid size={32} color={Colors.primary} />,
    targetRoute: '/',
    position: 'top',
  },
  {
    id: 'calendar-view',
    title: 'Schedule Management',
    description: 'Use the calendar to view all appointments, schedule new jobs, and manage your team\'s workload.',
    icon: <Calendar size={32} color={Colors.primary} />,
    targetRoute: '/',
    position: 'center',
  },
  {
    id: 'add-job',
    title: 'Create Jobs Quickly',
    description: 'Tap the + button to create a new service job. Add customer details, assign technicians, and set priority levels.',
    icon: <Plus size={32} color={Colors.primary} />,
    targetRoute: '/',
    position: 'bottom',
  },
  {
    id: 'customers-tab',
    title: 'Customer Management',
    description: 'Let\'s explore your customer database. Here you can manage contacts, equipment, and service history.',
    icon: <Users size={32} color={Colors.primary} />,
    targetRoute: '/customers',
    position: 'top',
    actionLabel: 'View Customers',
  },
  {
    id: 'customer-details',
    title: 'Detailed Customer Profiles',
    description: 'Each customer has a complete profile with contact info, equipment list, service history, and invoices.',
    icon: <Target size={32} color={Colors.primary} />,
    targetRoute: '/customers',
    position: 'center',
  },
  {
    id: 'add-customer',
    title: 'Adding Customers',
    description: 'Add new customers with their contact info, location, and equipment details for better service tracking.',
    icon: <Plus size={32} color={Colors.primary} />,
    targetRoute: '/customers',
    position: 'bottom',
  },
  {
    id: 'invoices-tab',
    title: 'Invoice & Revenue Management',
    description: 'Now let\'s check out invoicing. Track payments, create professional invoices, and manage your cash flow.',
    icon: <FileText size={32} color={Colors.primary} />,
    targetRoute: '/invoices',
    position: 'top',
    actionLabel: 'View Invoices',
  },
  {
    id: 'invoice-status',
    title: 'Track Payment Status',
    description: 'Filter invoices by status: draft, sent, paid, or overdue. Never miss a payment again.',
    icon: <CheckCircle2 size={32} color={Colors.success} />,
    targetRoute: '/invoices',
    position: 'center',
  },
  {
    id: 'tracking-tab',
    title: 'Real-Time Technician Tracking',
    description: 'Monitor your field team in real-time. See who\'s available, on route, or at a job site.',
    icon: <MapPin size={32} color={Colors.primary} />,
    targetRoute: '/tracking',
    position: 'top',
    actionLabel: 'View Tracking',
  },
  {
    id: 'technician-status',
    title: 'Team Status at a Glance',
    description: 'Track each technician\'s location, current job, and availability status for efficient dispatching.',
    icon: <Zap size={32} color={Colors.warning} />,
    targetRoute: '/tracking',
    position: 'center',
  },
  {
    id: 'more-tab',
    title: 'Settings & Advanced Features',
    description: 'Let\'s explore the More tab where you\'ll find additional tools and settings.',
    icon: <Settings size={32} color={Colors.primary} />,
    targetRoute: '/more',
    position: 'top',
  },
  {
    id: 'team-management',
    title: 'Manage Your Team',
    description: 'Add team members, assign roles, manage schedules, and track performance from Team Management.',
    icon: <Users size={32} color={Colors.primary} />,
    targetRoute: '/more',
    position: 'center',
  },
  {
    id: 'company-info',
    title: 'Company Branding',
    description: 'Set up your company details, logo, and business hours. This info appears on invoices and customer communications.',
    icon: <Building size={32} color={Colors.primary} />,
    targetRoute: '/more',
    position: 'center',
  },
  {
    id: 'reports-analytics',
    title: 'Business Intelligence',
    description: 'Access detailed reports on revenue, job completion rates, and customer insights to grow your business.',
    icon: <TrendingUp size={32} color={Colors.success} />,
    targetRoute: '/more',
    position: 'center',
  },
  {
    id: 'messaging',
    title: 'Team Communication',
    description: 'Message technicians directly, share job updates, and keep everyone connected in real-time.',
    icon: <MessageSquare size={32} color={Colors.primary} />,
    targetRoute: '/more',
    position: 'center',
  },
  {
    id: 'notifications',
    title: 'Stay Updated',
    description: 'Enable notifications to get instant alerts about job updates, payments, and team messages.',
    icon: <Bell size={32} color={Colors.primary} />,
    targetRoute: '/more',
    position: 'center',
  },
  {
    id: 'complete',
    title: 'You\'re All Set! 🎉',
    description: 'You\'re ready to manage your service business like a pro! Explore the app and discover even more features as you go.',
    icon: <Star size={32} color={Colors.success} />,
    targetRoute: '/',
    position: 'center',
    completedMessage: 'Tour completed! Start growing your business.',
  },
];

export const technicianProgressiveTour: ProgressiveTourStep[] = [
  {
    id: 'welcome',
    title: 'Welcome, Technician!',
    description: 'Let\'s get you familiar with how to manage your daily jobs, track time, and communicate with your team.',
    icon: <Wrench size={32} color={Colors.primary} />,
    targetRoute: '/',
    position: 'center',
  },
  {
    id: 'daily-schedule',
    title: 'Your Daily Schedule',
    description: 'Here are all your assigned jobs for today. Jobs are organized by time and priority so you know what\'s urgent.',
    icon: <Calendar size={32} color={Colors.primary} />,
    targetRoute: '/',
    position: 'top',
  },
  {
    id: 'job-card',
    title: 'Job Details at a Glance',
    description: 'Each job card shows customer name, location, time, and priority. Tap any job to see full details.',
    icon: <BookOpen size={32} color={Colors.primary} />,
    targetRoute: '/',
    position: 'center',
  },
  {
    id: 'job-status',
    title: 'Update Job Status',
    description: 'Always update your status: On Route → At Job → In Progress → Completed. This keeps the office informed.',
    icon: <Clock size={32} color={Colors.primary} />,
    targetRoute: '/',
    position: 'bottom',
  },
  {
    id: 'customer-info',
    title: 'Customer Information',
    description: 'Access customer contacts, service history, and equipment details. Tap to call or get directions instantly.',
    icon: <Users size={32} color={Colors.primary} />,
    targetRoute: '/customers',
    position: 'top',
    actionLabel: 'View Customers',
  },
  {
    id: 'equipment-history',
    title: 'Equipment & Service History',
    description: 'Review equipment details and past service notes before starting work. Knowledge is power!',
    icon: <Wrench size={32} color={Colors.primary} />,
    targetRoute: '/customers',
    position: 'center',
  },
  {
    id: 'photo-notes',
    title: 'Document Your Work',
    description: 'Take photos, add notes, and capture customer signatures. All documentation is saved automatically.',
    icon: <Shield size={32} color={Colors.primary} />,
    targetRoute: '/',
    position: 'center',
  },
  {
    id: 'messaging',
    title: 'Stay Connected',
    description: 'Message the office or other technicians. Share updates, ask questions, or request parts instantly.',
    icon: <MessageSquare size={32} color={Colors.primary} />,
    targetRoute: '/more',
    position: 'center',
  },
  {
    id: 'profile-settings',
    title: 'Your Profile & Settings',
    description: 'Update your availability, certifications, and skills. Keep your profile current for better job assignments.',
    icon: <Settings size={32} color={Colors.primary} />,
    targetRoute: '/more',
    position: 'center',
  },
  {
    id: 'complete',
    title: 'Ready to Work! 💪',
    description: 'You\'re all set! Remember to update job statuses and stay in touch with your team. Have a great day!',
    icon: <Star size={32} color={Colors.success} />,
    targetRoute: '/',
    position: 'center',
    completedMessage: 'Tour completed! Let\'s get to work.',
  },
];

export const quickProgressiveTour: ProgressiveTourStep[] = [
  {
    id: 'welcome',
    title: 'Quick Start Guide',
    description: 'Let\'s quickly show you the essentials so you can start using the app right away.',
    icon: <Zap size={32} color={Colors.primary} />,
    targetRoute: '/',
    position: 'center',
  },
  {
    id: 'navigation',
    title: 'Easy Navigation',
    description: 'Use the bottom tabs to switch between Schedule, Customers, Invoices, Tracking, and More.',
    icon: <Grid size={32} color={Colors.primary} />,
    targetRoute: '/',
    position: 'bottom',
  },
  {
    id: 'create-job',
    title: 'Create Your First Job',
    description: 'Tap the + button to create a new service job. It\'s quick and easy!',
    icon: <Plus size={32} color={Colors.primary} />,
    targetRoute: '/',
    position: 'center',
  },
  {
    id: 'complete',
    title: 'That\'s It!',
    description: 'You\'re ready to go! Explore and discover more features as you use the app.',
    icon: <CheckCircle2 size={32} color={Colors.success} />,
    targetRoute: '/',
    position: 'center',
  },
];
